language: java

jdk:
  - openjdk8

branches:
  only:
#    - [ input deploy branchs ]

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

notifications:
#  webhooks: [ input telegram url ]