# command : docker-compose up -f docker-compose-persistence.yml -d mysql
version: "2.1"
  mysql:
    image: mysql:5.6
    container_name: mysql
    command: --lower_case_table_names=1
    environment:
      - TZ=Asia/Seoul
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_DATABASE=kanban
    ports:
      - "3306:3306"
    volumes:
      - ./volume/mysql/script/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./volume/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "-uroot", "-proot",  "ping", "-h", "localhost"]
      interval: 20s
      timeout: 3s
      retries: 5

#  redis:
#    image: 'redis:latest'
#    container_name: redis
#    environment:
#      - ALLOW_EMPTY_PASSWORD=yes
#      - DISABLE_COMMANDS=CONFIG
#    ports:
#      - '6379:6379'
#    volumes:
#      - ./volume/redis/data:/redis/data
#    restart: always