version: "2.1"
services:
  app:
    build: kanban-app
    image: devstream/kanban/app:latest
    environment:
      - SPRING_PROFILE=production
      - JVM_MEMORY=-Xmx4g -Xms4g -XX:MetaspaceSize=200m
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/healthcheck"]
      interval: 30s
      timeout: 60s
      retries: 15

  web:
    build: kanban-web
    image: devstream/kanban/web:latest
    ports:
      - 8081:8081
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/healthcheck"]
      interval: 30s
      timeout: 60s
      retries: 15

  nginx:
    build: kanban-nginx
    image: devstream/kanban/nginx:latest
    ports:
      - 80:80
      - 443:443
    links:
      - app:app
      - web:web
    depends_on:
      app:
        condition: service_healthy
      web:
        condition: service_healthy